### ISSUE TITLE
Add dummy documents

### ISSUE THREAD

**Issue by hannoL** [honeynet/droidbot#10]
In order to see behavior of android-crypto-lockers like (simplelocker - bd827e42a9a8e13e2d138ccdfef0d7fa4ab3e67a1dbc39bea8b53d1fb085154f) droitBot should add some dummy pictures, pdfs, docs, ... in the emulator-image before installing the malware.

**Comment by aikinci** [comment]
+1

**Comment by ylimit** [comment]
Finished in commit 1a511432ffe29027f816f4ad1b886bf3f2cd24ef.
