### ISSUE TITLE
WARNING:DroidBotIme:Failed to disconnect DroidBotIME

### ISSUE THREAD

**Issue by littleyee** [honeynet/droidbot#100]
Hi I have encountered the following issue. Any ideas? 

WARNING:Device:Seems like you are using an emulator. If so, please add is_emulator option.
INFO:DroidBot:Starting DroidBot
INFO:Device:waiting for device
62733
PID: 5733
INFO: Using projection 1080x1920@1080x1920/0
INFO: (external/MY_minicap/src/minicap_26.cpp:241) Creating SurfaceComposerClient
INFO: (external/MY_minicap/src/minicap_26.cpp:244) Performing SurfaceComposerClient init check
INFO: (external/MY_minicap/src/minicap_26.cpp:255) Creating virtual display
INFO: (external/MY_minicap/src/minicap_26.cpp:261) Creating buffer queue
ERROR: (external/MY_minicap/src/minicap_26.cpp:281: errno: None) Unable to find neither AOSP nor O Developer Preview 1 BufferQueue::createBufferQueue
ERROR: (jni/minicap/minicap.cpp:383: errno: None) Unable to start minicap with current config
INFO: (external/MY_minicap/src/minicap_26.cpp:312) Destroying virtual display
62734
failed to clear the 'main' log
Traceback (most recent call last):
  File "/Users/xuasong/droidbot/droidbot/droidbot.py", line 143, in start
    self.device.connect()
  File "/Users/xuasong/droidbot/droidbot/device.py", line 154, in connect
    adapter.connect()
  File "/Users/xuasong/droidbot/droidbot/adapter/logcat.py", line 29, in connect
    self.device.adb.run_cmd("logcat -c")
  File "/Users/xuasong/droidbot/droidbot/adapter/adb.py", line 64, in run_cmd
    r = subprocess.check_output(args).strip()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['adb', '-s', 'emulator-5554', 'logcat', '-c']' returned non-zero exit status 1.
[CONNECTION] ADB is disconnected
[CONNECTION] Minicap is disconnected
WARNING:DroidBotIme:Failed to disconnect DroidBotIME!

**Comment by ylimit** [comment]
Please give more details on what device/app/command you used.

**Comment by littleyee** [comment]
wireless-nat-guest-inside:platform-tools user$ droidbot -a /Users/user/Downloads/Get-Notification-master/APKs/com.abc.abcnews_33200000_apps.evozi.com.apk -o /Users/user/Downloads/Get-Notification-master/Output
WARNING:Device:Seems like you are using an emulator. If so, please add is_emulator option.
INFO:DroidBot:Starting DroidBot
INFO:Device:waiting for device
62733
PID: 5733
INFO: Using projection 1080x1920@1080x1920/0
INFO: (external/MY_minicap/src/minicap_26.cpp:241) Creating SurfaceComposerClient
INFO: (external/MY_minicap/src/minicap_26.cpp:244) Performing SurfaceComposerClient init check
INFO: (external/MY_minicap/src/minicap_26.cpp:255) Creating virtual display
INFO: (external/MY_minicap/src/minicap_26.cpp:261) Creating buffer queue
ERROR: (external/MY_minicap/src/minicap_26.cpp:281: errno: None) Unable to find neither AOSP nor O Developer Preview 1 BufferQueue::createBufferQueue
ERROR: (jni/minicap/minicap.cpp:383: errno: None) Unable to start minicap with current config
INFO: (external/MY_minicap/src/minicap_26.cpp:312) Destroying virtual display
62734
failed to clear the 'main' log
Traceback (most recent call last):
  File "/Users/droidbot/droidbot/droidbot.py", line 143, in start
    self.device.connect()
  File "/Users/user/droidbot/droidbot/device.py", line 154, in connect
    adapter.connect()
  File "/Users/user/droidbot/droidbot/adapter/logcat.py", line 29, in connect
    self.device.adb.run_cmd("logcat -c")
  File "/Users/user/droidbot/droidbot/adapter/adb.py", line 64, in run_cmd
    r = subprocess.check_output(args).strip()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['adb', '-s', 'emulator-5554', 'logcat', '-c']' returned non-zero exit status 1.
[CONNECTION] ADB is disconnected
[CONNECTION] Minicap is disconnected
WARNING:DroidBotIme:Failed to disconnect DroidBotIME!

**Comment by ylimit** [comment]
Still don't what device you are using.
Could you please try different devices or emulators?
