### ISSUE TITLE
How to improve the test method to fit the app

### ISSUE THREAD

**Issue by qibinaoe** [honeynet/droidbot#109]
Hello!
When I used the app to test some apps, I found sometimes it could not enter another activity I means it always stayed at an state and no change. So I want to write the script, but I found I should know the class name and id of the app in advance. But when I use the droidbot to test others' app, it would be inconvenient to know the definite class name.
So is it a must to know the class name and some necessary information of the app if I want to use the script?
Thanks!

**Comment by ylimit** [comment]
Sorry for the very late reply.
To use the script, usually you need to know the resource-ids of the actions to navigate into your target state. You can obtain these ids using the Android uiautomator tool.
