### ISSUE TITLE
errors in test cases

### ISSUE THREAD

**Issue by thakurakhil** [honeynet/droidbot#12]
I found few issues with the unittest cases for the droidbot, please correct me if i'm wrong.
**issue#1.**
In test_types.py (in tests folder) , in the function test_is_foreground , 
in line 42 -> "settings_app = App(package_name="com.android.settings")"
the class App has no keyword as "package_name" in the argument instead there is "path_name" , so if we had to use the path for the settings app then we have to be previliged but phone would not be rooted for this to happen.
in line 43 -> no_app = App()
the class app requires atleast one parameter (i.e. path_name), even if we send None as parameter in the class app we are asserting it to not be None.

**issue#2.**
In test_droid.py (in tests folder), in the function setUp ,
in line 8 -> "self.droidbot = DroidBot(device_serial="emulator-5554", event_duration=10)" , the Droidbot class in meant to be initialized with an app. below is the init func of Droidbot class. Here the app_path must have to be sent inorder for initialization but it's not sent as argument. Even if we initialize it with None we will be getting error in Line 47 of droidbot.py file.

def **init**(self, app_path, device_serial=None, output_dir=None,
                 env_policy=None, event_policy=None, with_droidbox=False,
                 event_count=None, event_interval=None, event_duration=None, quiet=False):

**issue#3.**
In test_types.py (in tests folder), in the function test_settings,
in line 97(similar is the case with line 99) -> "self.assertEqual(self.device.get_settings()['system']['volume_system'], '10')" , the get_settings() function for device from types.py would get the data from the db "/data/data/com.android.providers.settings/databases/settings.db" , where as for an newly created emulator this db would be empty and hence would get "no table with name system" error. as a work around for emulator devices we could use the backup db which lies in "/data/data/com.android.providers.settings/databases/settings.db-backup"

**Comment by lynnlyc** [comment]
Sorry I didn't update the unit tests after committed a new version.
I will fix them ASAP.
BTW your suggestions are very helpful. :)

**Comment by ylimit** [comment]
The test cases are deprecated for a long time, so I've deleted all of them in the latest commit.
I will open a new issue for test cases.
