### ISSUE TITLE
hybrid app test

### ISSUE THREAD

**Issue by Gunkkk** [honeynet/droidbot#135]
Since the accessibility for  hybrid app  can not always work, it is hard for Droidbot  to test a hybrid app. Is there any update schdule for that?

**Comment by yuanchun-li** [comment]
Thanks for asking. Hybrid apps are indeed difficult for the current version of DroidBot. We have a `-cv` command line option that will extract UI elements from the screenshots using computer vision techniques, but it is currently very elementary.
We plan to use deep learning to enhance the vision-based testing strategy, but we don't have a schedule yet.

**Comment by Gunkkk** [comment]
> that

Thank you for your reply.   I think the vision-based case generation will be a good solution and it seems that there is no related  work yet.  Looking forward to your work.
