### ISSUE TITLE
Android versions supported by DroidBot

### ISSUE THREAD

**Issue by Connor-fire** [honeynet/droidbot#148]
What are the Android versions currently supported by DroidBot?  Looking forward to your reply.  Thank you so much.

**Comment by yuanchun-li** [comment]
The latest supported version should be Android 31.
Later versions are not supported mainly because they are not supported by the minicap library.
https://github.com/honeynet/droidbot/tree/master/droidbot/resources/minicap/jni/libs

**Comment by yuanchun-li** [comment]
Sure. To support Android 32, the key is to upgrade the [minicap library](https://github.com/DeviceFarmer/minicap) which is used to capture screenshot in droidbot. Unfortunately, it seems the minicap library is no longer maintained.
So you may need to find another way to capture the screenshot. I used `adb shell screencap` command before, but it was slow. If obtaining the screenshots is not necessary for you, you may try to set `self.adapters[self.minicap]` to False in device.py to see whether it works.

**Comment by Niweera** [comment]
@yuanchun-li thank you for the input. Actually, I don't need the screen-capturing feature for my purpose. So I will try your suggestion. 
Thanks again for your help.

Regards.

**Comment by Niweera** [comment]
Hi @yuanchun-li,

I am updating your scripts to support Android 32. I will send you a PR once I am done (if that's okay with you). 

Best.

**Comment by yuanchun-li** [comment]
Sure. Please go ahead.
