### ISSUE TITLE
Storing device states in droidbot

### ISSUE THREAD

**Issue by nastya** [honeynet/droidbot#20]
I have a problem obtaining device states.

I run droidbot with this command:
`droidbot -d emulator-5554 -a filename.apk -event state_recorder -duration 100 -o droidbot_out`
It works fine but after finishing the analysis there is no subdirectory `device_states` in `droidbot_out`.

I've spent some time trying to understand why the states are not stored and revealed that it is caused by exception in function get_view_str of DeviceState ([droidbot_types.py#L632-L640](https://github.com/honeynet/droidbot/blob/master/droidbot/droidbot_types.py#L632-L640)). Map returned by a viewclient does not contain fields 'package', 'resource-id' and 'text' so referring to them causes exception.

I substituted this function by
  ```py 
  def get_view_str(view_dict):
        """
        get the unique string which can represent the view
        @param view_dict: dict, element of list device.get_current_state().views
        @return:
        """
        view_str = "package:%s,class:%s,resource-id:%s,text:%s" %\
                   (view_dict['package'] if 'package' in view_dict else 'nopackage',\
                    view_dict['class'] if 'class' in view_dict else 'noclass',\
                    view_dict['resource-id'] if 'resource-id' in view_dict else 'noresource-id',\
                    view_dict['text'] if 'text' in view_dict else 'notext')
        return view_str
```

This way I obtained some devices states .json and .png files. Here is an example:

[device_state_2016-07-07_155937.json.txt](https://github.com/honeynet/droidbot/files/354302/device_state_2016-07-07_155937.json.txt)

We can see in returned maps keys "uniqueId" instead of "resource-id" and "text:mText" instead of "text" for TextViews. I think they can be used to obtain unique view_str for a view.

Is it a bug in droidbot or my androidviewclient does not work properly?

**Comment by ylimit** [comment]
It is a bug in droidbot, I assumed the `view_dict` returned by viewclient always has the keys.

Thank you.

**Comment by ylimit** [comment]
Hello, I investigated this issue further and found that:

androidviewclient produce different view_dict with "forceviewserveruse" option turned on or off.
(See `get_view_client` method in `droidbot_types.py`.)

If it is set to False, saving states in droidbot works well, but it does not support Android version 4.3-.
If it is set to True, androviewclient is compatible to all Android versions, however saving state does not work properly.

I am working on this issue now, and I will let you know once fixed.

**Comment by ylimit** [comment]
Should be fixed in latest commit.
