### ISSUE TITLE
Question about Android 6.0 Support

### ISSUE THREAD

**Issue by mingwayzhang** [honeynet/droidbot#24]
Hi,

I am glad to see this project is still active. Could you let me know if the project supports marshmallow or not? Thanks a lot!

**Comment by ylimit** [comment]
Yes.

**Comment by mingwayzhang** [comment]
Thanks a lot!

But could you clarify that, since this repo seems only contain 4.1.1 image. How may I use it for marshmallow?

**Comment by mingwayzhang** [comment]
OK. So Droidbot is using Droidbox, which is based on static apk instrumentation using androguard. Everything else here is pretty much android version independent. That's why Droidbot is agnostic to Android versions, right?

**Comment by ylimit** [comment]
Hello, you can use DroidBot on any device.
Using with DroidBox is just a recommended way to do dynamic analysis, as DroidBox is able to monitor sensitive behaviours at runtime.

To use DroidBot with Android 6.0, you need to:
1. start a Android 6.0 emulator or connect to a Android 6.0 device via ADB;
2. get the device serial no using `adb devices`;
3. start droidbot with `droidbot -a <xxx.apk> -d <serial no> -event ... -env ...`

**Comment by mingwayzhang** [comment]
Thanks for the clarification!

Another question is that what is the "taint" feature in droidbot.py?

**Comment by ylimit** [comment]
DroidBox can track sensitive information flow using taint tracking (based on [TaintDroid](http://www.appanalysis.org/)). 
Thus the taint feature is in DroidBox instead of DroidBot.
Did I understand your question correctly?

**Comment by mingwayzhang** [comment]
Thanks for the information. Yes.
