### ISSUE TITLE
Screenshots are not generated in Windows

### ISSUE THREAD

**Issue by rupak0577** [honeynet/droidbot#37]
As a result of commit 997c16be3659a09f0c11f317abf4e78abe4f7d55, the screenshots are now captured with adb and pulled from the device to the `temp` directory. Although this works fine in Linux, for some reason it does not on Windows. The following issues were discovered -

1. The screenshots are not generated in the `states` directory.

2. The screenshots, although removed at the end, are still shown by Explorer.

3.  A `WARNING:Device:saving state to dir failed:` is logged. This is due to a `[Error 2] The system cannot find the file specified` exception thrown [here](https://github.com/honeynet/droidbot/blob/997c16be3659a09f0c11f317abf4e78abe4f7d55/droidbot/device.py#L808)

**Comment by ylimit** [comment]
Replaced `cp` with `shutil.copyfile`.
However, since droidbot has not been tested on Windows, other problems may remain.
