### ISSUE TITLE
Feedbacks from ICSE 2017

### ISSUE THREAD

**Issue by ylimit** [honeynet/droidbot#39]
Would be interesting to explore:

- Test large-scale apps such as WeChat.
- Estimate power consumption by running an app with the same input for hundreds of times.
- Support record and replay.
- Reproducible test.
- Can we do something with CrashScope (another interesting demo in ICSE 2017)?
- Testing game apps?

**Comment by FAndSec** [comment]
Hi, may I know if you have implemented/are implementing reproducible test module? If I understand correctly, that should mean repeating tests from last runs. 
If not, I may try to contribute that part. Goal is to add as a test policy: repeat

**Comment by ylimit** [comment]
Hi @FAndSec , your understanding is correct, and it's not implemented yet. Your contribution will be much appreciated.
