### ISSUE TITLE
Inquiry for how to use Droidbot with Droidbox

### ISSUE THREAD

**Issue by zhang-li** [honeynet/droidbot#55]
Hi, thanks for sharing this tool. I see in your post that you do the evaluation using Droidbox. May I know how do you do that?

I mean, for droidbox, I need to use command:
    ./droidbox.sh <file.apk> <duration in secs (optional)>

and for droidbot, I need to use command:
    droidbot -a <path_to_apk> -o output_dir

Both install the app into the AVD, won't there be some conflict?

**Comment by ylimit** [comment]
Please checkout the 1.0.2b1 tag, in which we have an option to start DroidBot with DroidBox.

**Comment by zhang-li** [comment]
Thanks for your prompt reply. I tried to 1.0.2b1 version and see the option -use_with_droidbox. 
I started the droidbox emulator with ./startemu.sh test_droidbox. (Need I run ./droidbox.sh?)

Then I tried to start droidbot with droidbot -d emulator-5554 -a myapp.apk -use_with_droidbox. However, it reports the following error. May I know what are the possible reasons?
If possible, will you please share some detailed steps on how you perform the analysis together with Droidbox?

Traceback (most recent call last):
  File "/home/csi/droidbot/droidbot/droidbot.py", line 78, in __init__
    self.droidbox = DroidBox(droidbot=self, output_dir=self.output_dir)
  File "/home/csi/droidbot/droidbox_scripts/droidbox.py", line 80, in __init__
    self.state_monitor = self.droidbot.device.state_monitor
AttributeError: 'Device' object has no attribute 'state_monitor'
error: listener 'tcp:7335' not found

error: listener 'tcp:7336' not found

**Comment by zhang-li** [comment]
I need to perform some dynamic analysis on Android apps and extract the analysis report. Is it possible to use the newest version of Droidbot together with sandbox like Droidbox or CuckooDroid?

**Comment by ylimit** [comment]
I removed the DroidBox module in the newest version of DroidBot, but it can work with those sandboxes.
For example, DroidBox logs sensitive operations in logcat, so maybe you can try:
1. Start emulator with the DroidBox image;
2. Start DroidBot (instead of using droidbox.sh);
3. After DroidBot is finished, parse the logcat file in DroidBot's output dir to extract all sensitive operations.
