### ISSUE TITLE
customize input discuss

### ISSUE THREAD

**Issue by michelleXue** [honeynet/droidbot#56]
Hi,

Can you show me more details about how to use the customize input?
In your `pass_login_script.jason` example:

```
    "views": {
        "login_email": {
            "resource_id": ".*email",
            "class": ".*EditText"
        },
```
how can I link this view to the actual login view at runtime, so that droidbot will know which view it should insert these inputs? What is the meaning of the label such as `"login_email"`?
And what are the `states` and `operations`? 

Thank you!

**Comment by yzygitzh** [comment]
Hi,

The testing script describes that given a **UI state**, **what would droidbot do**.

The state indicates **UI state**, and is identified by matching views in it. For example, in `pass_login_script.json`, one wants to identify the login screen, so one declares that once a state has `login_email`, `login_password` and `login_button` views, it's a `login_state`. Views are matched by regular expressions of its attributes including `resource_id` and `class`, which can be found by UIAutomator or Accessibility Service.

The operation indicates **what would droidbot do**. Operation has many types, in this example includes "set_text" meaning setting contents of a TextView, "touch" meaning touching the view, etc.

Hope the above helps.

**Comment by michelleXue** [comment]
Great! Thanks for the explanation.
