### ISSUE TITLE
Is droidbotApp.apk source code available?

### ISSUE THREAD

**Issue by ClaudiuGeorgiu** [honeynet/droidbot#57]
Hi, I'm doing some tests with droidbot and I would like to study how it works. Since [droidbotApp.apk](https://github.com/honeynet/droidbot/blob/4151121c0fa13813c3975dbeb44c95f45936a5fc/droidbot/resources/droidbotApp.apk) has to be installed on the device for droidbot to work, I would like to know if the source code of this app is available. Thank you in advance.

**Comment by ylimit** [comment]
Okay I just open-sourced it at:
https://github.com/ylimit/droidbotApp
However, the code is in low quality currently and may be hard to read.
Please feel free to ask questions.
