### ISSUE TITLE
Webview Support

### ISSUE THREAD

**Issue by michelleXue** [honeynet/droidbot#58]
Hi,

I have a quick question about webview support.
Does your tool currently support webview or just view?
If not, is there any way we can integrate the webview?

Thank you!

**Comment by ylimit** [comment]
DroidBot is based on UIAutomator, and UIAutomator can inspect WebView from Android 4.4 (see https://developer.android.com/guide/webapps/migrating.html).
However, from my experience on using DroidBot for WebView, sometimes it works while sometimes not. The reasons might be (I'm not sure):
1. The app developers use setWebContentsDebuggingEnabled(false) to disable debugging for their webpage;
2. The device or app uses a different version of browser engine.

**Comment by michelleXue** [comment]
Good to know, thanks for the explanation.

**Comment by Dado1513** [comment]
Hi,
 I have investigated several apps with webview but it seems to work correctly, maybe because it's now based on accessibility service instead uiautomator ? Do you know any app with webview that does not work ?
