### ISSUE TITLE
Port to python 3

### ISSUE THREAD

**Issue by ylimit** [honeynet/droidbot#63]

**Comment by ClaudiuGeorgiu** [comment]
Hi, I would like to help with this, do you have any roadmap?

**Comment by ylimit** [comment]
Thank you very much @ClaudiuGeorgiu .
I don't have a roadmap for this. Could you install and test DroidBot with Python 3 and see what happens?

**Comment by ClaudiuGeorgiu** [comment]
Sure, I will test it in the next days and I will report here the results.

**Comment by ClaudiuGeorgiu** [comment]
Hi, I've started updating the code (https://github.com/ClaudiuGeorgiu/droidbot/commits/python3). It looks like that the last version of androguard introduced some changes in how the manifest is handled so droidbot needs to be updated accordingly. I'll investigate more in the next days and I'll report back here the progress.

**Comment by ClaudiuGeorgiu** [comment]
Hi @ylimit, I've finally managed to run DroidBot with Python3 but I don't think the changes are compatible with Python2 (I wasn't interested in maintaining the compatibility). I'm going to continue working on my fork of DroidBot to do some minor refactoring/add some minor features for my use case, so let me know if you are interested in a pull request.

**Comment by ylimit** [comment]
Thank you very much @ClaudiuGeorgiu .
I just created a python3 branch. Please pull your code to that branch.

**Comment by anant-joshi** [comment]
Hi, I would also like to help with this. Is there anything left to do in this?

**Comment by ClaudiuGeorgiu** [comment]
Hi @anant-joshi, I just added basic `Python3` compatibility (see the `python3` branch). Currently I'm working on the following things:
- [ ] use `logger.something` instead of `print` (so that all the code is consistent)
- [ ] use `.format(...)` instead of `%` in strings
- [ ] fix typos and update docstrings (this has nothing to do directly with `Python3`)

Let me know if you want to help with this.

@ylimit, what do you think about this list of tasks?

**Comment by anant-joshi** [comment]
Sure, sounds good.

**Comment by anant-joshi** [comment]
I've converted all strings from % to .format().
Here: 1ff2a4e1ad3cdec7fa65e2a35a29ccd51a4a80a3

**Comment by Erick2206** [comment]
Hey @ClaudiuGeorgiu can I work on porting print statements to loggers?

**Comment by ClaudiuGeorgiu** [comment]
@Erick2206 yes, of course.

**Comment by Erick2206** [comment]
@ClaudiuGeorgiu  so I have to port all print statements to logger statements, right?

**Comment by ClaudiuGeorgiu** [comment]
@Erick2206 yes. For example if you find a print statement inside an `except` block you can convert it to `logger.error(...)` or `logger.warning(...)`, depending on the severity of the error.

**Comment by Erick2206** [comment]
@ClaudiuGeorgiu  I have sent a pull request, please review it and merge if correct.

**Comment by ClaudiuGeorgiu** [comment]
@Erick2206 I reviewed the pull request. However I can't merge pull requests, you will have to wait for someone with write access to the repository.

**Comment by Jayd-1234** [comment]
Hi @ClaudiuGeorgiu , I would like to contribute to towards the porting process. How can I help?

**Comment by ClaudiuGeorgiu** [comment]
Thanks @Jayd-1234 but at the moment I don't know what else has to be ported to Python3, but if you have any idea just open a new pull request.

**Comment by ylimit** [comment]
The master branch now supports Python 3. Not well-tested though.

**Comment by YurieCo** [comment]
**Please include in the description that it does support Python3 !!!**
