### ISSUE TITLE
Dockerizing droidbot

### ISSUE THREAD

**Issue by Erick2206** [honeynet/droidbot#73]
@ylimit  Would it be a good idea to dockerize the application? It would add a virtualized environment that would remain consistent over all systems but do you think that the overhead would be greater than the benefits?

**Comment by hannoL** [comment]
I think the opportunity that someone new runs the tool without any setup in docker is great. But nevertheless anybody who wants to run droidbot in a production setup has to optimize it for himself (properly without docker).
But adding a Dockerfile to the repository, does not break the opportunity for current users to use it without Docker.

**Comment by Erick2206** [comment]
And also I think it will solve issues like #76 , any opinion @ylimit ?
