### ISSUE TITLE
Error on running droidbot

### ISSUE THREAD

**Issue by gnr19911** [honeynet/droidbot#74]
When I am running droidbot I get following error
`WARNING:DroidBot:Something went wrong: 'APK' object has no attribute 'get_AndroidManifest'
Traceback (most recent call last):
  File "/home/gopesh/droidbot/droidbot/droidbot.py", line 87, in __init__
    self.app = App(app_path, output_dir=self.output_dir)
  File "/home/gopesh/droidbot/droidbot/app.py", line 35, in __init__
    self.get_activities()
  File "/home/gopesh/droidbot/droidbot/app.py", line 76, in get_activities
    manifest = self.get_androguard_analysis().a.get_AndroidManifest()
AttributeError: 'APK' object has no attribute 'get_AndroidManifest'
Error: Unknown id: com.android.inputmethod.latin/.LatinIME
WARNING:DroidBotIme:Failed to disconnect DroidBotIME!
[CONNECTION] ADB is disconnected
`

**Comment by Erick2206** [comment]
@gnr19911  What command did you use?

**Comment by gnr19911** [comment]
@Erick2206  droidbot -a myapp.apk -o output_dir

**Comment by Erick2206** [comment]
Did you install droidbot as mentioned [here](https://github.com/honeynet/droidbot#how-to-install) with all the dependencies installed?

**Comment by ddlucad96** [comment]
Same problem here

Ubuntu 16.04

**Comment by ClaudiuGeorgiu** [comment]
@gnr19911 @ddlucad96 if you are using `Python2` then you have to install the correct version of Androguard: `androguard==3.0.1`. That's because the latest version of Androguard (`3.1.0`) was released recently and introduced some breaking changes.

**Comment by ddlucad96** [comment]
@ClaudiuGeorgiu Thanks but it didn't work.

I've managed to **fix** it changing in the code the line 76 from:
`manifest = self.get_androguard_analysis().a.get_AndroidManifest()`
to:
`manifest = self.get_androguard_analysis().a.get_android_manifest_xml()`

I'm going to make a pull request if have some free time.

**Comment by ylimit** [comment]
Thanks @ddlucad96
