### ISSUE TITLE
input script not able to fill textboxes

### ISSUE THREAD

**Issue by freefire4547** [honeynet/droidbot#82]
I created my script to fill textfields in login form of the app. The cursor in the app moves from one textfield to another one by one, but the problem is it does not fill values in any of the textfields.

The script that I created is
`{
      "views":
       {
         "first_name": {
            "resource_id": ".*editText5",
            "class": ".*EditText"
        },
        "last_name": {
            "resource_id": ".*editText6",
            "class": ".*EditText"
        },
        "login_mobile": {
            "resource_id": ".*editText3",
            "class": ".*EditText"
        },
	"login_email": {
            "resource_id": ".*editText4",
            "class": ".*EditText"
        },
        "login_age": {
            "resource_id": ".*editText2",
            "class": ".*EditText"
        },
        "login_button": {
            "resource_id": ".*button9",
            "class": ".*Button"
        }
    },
    "states": {
        "login_state": {
            "views": ["first_name", "last_name", "login_mobile", "login_email", "login_age", "login_button"]
        }
    },
    "operations": {
        "login_operation": [
	    {
                "event_type": "set_text",
                "target_view": "first_name",
                "text": "Allen"
            },
	    {
                "event_type": "set_text",
                "target_view": "last_name",
                "text": "Peter"
            },
            {
                "event_type": "set_text",
                "target_view": "login_mobile",
                "text": "8989898989"
            },
            {
                "event_type": "set_text",
                "target_view": "login_email",
                "text": "sample@email.com"
            },
	    {
                "event_type": "set_text",
                "target_view": "login_age",
                "text": "20"
            },
            {
                "event_type": "touch",
                "target_view": "login_button"
            }
        ]
    },
    "main": {
        "login_state": ["login_operation"]
    }
}`

The generated log contain following lines
`INFO:AppEnvManager:Start deploying environment, policy is none
INFO:InputEventManager:start sending events, policy is dfs_greedy
Input: KeyEvent(state=061191e12a9a8c41fe7ea8e6619f7d68, name=HOME)
Input: IntentEvent(intent='am start 
INFO:DroidBotScript:matched state: login_state, taking operation: login_operation
Input: SetTextEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=c1478b7d52bf484296a9990a6d7700bb, text=Allen)
Input: SetTextEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=1da679f2bfe7911e4675a2399c1b04fe, text=Peter)
Input: SetTextEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=41a654a4d3ee82054229980f4f7e8727, text=8989898989)
Input: SetTextEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=0ab6494a1ae52a314512b916d40dfa55, text=sample@email.com)
Input: SetTextEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=e96a0859d0842b691003fcb389383179, text=20)
Input: TouchEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=f243b21ac8c5d0aee474db642b8993d9)
INFO:DroidBotScript:matched state: login_state, taking operation: login_operation
Input: SetTextEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=c1478b7d52bf484296a9990a6d7700bb, text=Allen)
Input: SetTextEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=1da679f2bfe7911e4675a2399c1b04fe, text=Peter)
Input: SetTextEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=41a654a4d3ee82054229980f4f7e8727, text=8989898989)
Input: SetTextEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=0ab6494a1ae52a314512b916d40dfa55, text=sample@email.com)
Input: SetTextEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=e96a0859d0842b691003fcb389383179, text=20)
Input: TouchEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=f243b21ac8c5d0aee474db642b8993d9)
INFO:DroidBotScript:matched state: login_state, taking operation: login_operation
Input: SetTextEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=c1478b7d52bf484296a9990a6d7700bb, text=Allen)
Input: SetTextEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=1da679f2bfe7911e4675a2399c1b04fe, text=Peter)
Input: SetTextEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=41a654a4d3ee82054229980f4f7e8727, text=8989898989)
Input: SetTextEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=0ab6494a1ae52a314512b916d40dfa55, text=sample@email.com)
Input: SetTextEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=e96a0859d0842b691003fcb389383179, text=20)
Input: TouchEvent(state=6c26177c7e7ea6ae7dcd190550b2eda6, view=f243b21ac8c5d0aee474db642b8993d9)
^CINFO:InputEventManager:Finish sending events
`

**Comment by freefire4547** [comment]
Also I noticed that it works well on real device, but have this issue on emulators.

**Comment by ClaudiuGeorgiu** [comment]
I had the same issue on the emulator, but it worked after I enabled and set DroidBot's keyboard as the default (from `Settings > Language & input > Current Keyboard` menu):
![image](https://user-images.githubusercontent.com/6818578/40199406-a2eb5b0e-5a19-11e8-8d56-35af9ba35c25.png)

**Comment by freefire4547** [comment]
@ClaudiuGeorgiu  Thanks ! it worked.
