### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getElementsByTagName'

### ISSUE THREAD

**Issue by rajneesh152** [honeynet/droidbot#85]
I am still facing the same issue. I had done all. You can refer below and please recommand what to do next to resolve issue;

WARNING:DroidBot:Something went wrong: 'NoneType' object has no attribute 'getElementsByTagName'
Traceback (most recent call last):
File "/home/amity/Downloads/droidbot/droidbot/droidbot.py", line 87, in init
self.app = App(app_path, output_dir=self.output_dir)
File "/home/amity/Downloads/droidbot/droidbot/app.py", line 35, in init
self.get_activities()
File "/home/amity/Downloads/droidbot/droidbot/app.py", line 77, in get_activities
for activity_dom in manifest.getElementsByTagName("activity"):
AttributeError: 'NoneType' object has no attribute 'getElementsByTagName'
[CONNECTION] ADB is disconnected
Error: Unknown id: com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME
WARNING:DroidBotIme:Failed to disconnect DroidBotIME!
root@amity:/home/amity/Downloads/droidbot/droidbot# pip install androguard==3.0.1
Requirement already satisfied: androguard==3.0.1 in /usr/local/lib/python2.7/dist-packages

Please help

**Comment by ylimit** [comment]
Hi, it seems like a problem of your app under test.
Could you please try other apps and see what happens?

BTW, I just pushed a new version, which is supposed to work with the lastest androguard.

**Comment by rajneesh152** [comment]
I have tried another application, now it is show the below:

droidbot -a /home/amity/Desktop/app-debug.apk -o output
WARNING:DroidBot:Something went wrong: local variable 'value' referenced before assignment
Traceback (most recent call last):
  File "/home/amity/Downloads/droidbot/droidbot/droidbot.py", line 87, in __init__
    self.app = App(app_path, output_dir=self.output_dir)
  File "/home/amity/Downloads/droidbot/droidbot/app.py", line 32, in __init__
    self.possible_broadcasts = self.get_possible_broadcasts()
  File "/home/amity/Downloads/droidbot/droidbot/app.py", line 150, in get_possible_broadcasts
    receivers = androguard_a.get_receivers()
  File "/usr/local/lib/python2.7/dist-packages/androguard/core/bytecodes/apk.py", line 463, in get_receivers
    return self.get_elements("receiver", "android:name")
  File "/usr/local/lib/python2.7/dist-packages/androguard/core/bytecodes/apk.py", line 378, in get_elements
    l.append( str( value ) )
UnboundLocalError: local variable 'value' referenced before assignment
[CONNECTION] ADB is disconnected
Error: Unknown id: com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME

I will also try new version for latest androguard. 

But please help me in this.

**Comment by ylimit** [comment]
It seems an internal error in androguard. Have you tried the newest version? If the problem remains, can you upload your app for us to reproduce the error?

**Comment by rajneesh152** [comment]
Not yet tried over newest version. 

Okay I just try over newest version, if got same then forward you .apk file.

**Comment by rajneesh152** [comment]
Hey, droidbot implementation got successful after updating from #84 . 

But it is working properly over androguard version 3.0.1 not for upper version.
