### ISSUE TITLE
Warning message while starting droidbot

### ISSUE THREAD

**Issue by jyotigajrani** [honeynet/droidbot#88]
we installed the tool successfully but when we start the tool it shows error that Please enable accessibility for DroidBot app manually.
I am attaching the screenshot also.
Please suggest how to enable accessibility.

Regards
Jyoti
![enable](https://user-images.githubusercontent.com/12912589/51897862-b6990a80-23d5-11e9-85af-24965a5660bc.png)

**Comment by yzygitzh** [comment]
Hi,
You can go to settings->accessibility and enable DroidBot app in it.

Regards,
Ziyue Yang

**Comment by jyotigajrani** [comment]
Thanks...It worked..
After this I get following error on terminal in continuation and could not see start of exploration....

`
[CONNECTION] Logcat is enabled and connected.
[CONNECTION] TelnetConsole is not enabled.
[CONNECTION] DroidBotIme is enabled and connected.
[CONNECTION] UserInputMonitor is enabled and connected.
[CONNECTION] ADB is enabled and connected.
[CONNECTION] ProcessMonitor is enabled and connected.
[CONNECTION] DroidBotAppConn is enabled and connected.
[CONNECTION] Minicap is not enabled.

Traceback (most recent call last):
  File "/home/jyoti/droidbot/device.py", line 803, in get_current_state
    views = self.get_views()
  File "/home/jyoti/droidbot/device.py", line 874, in get_views
    views = self.droidbot_app.get_views()
  File "/home/jyoti/droidbot/adapter/droidbot_app.py", line 244, in get_views
    view_tree['parent'] = -1
TypeError: 'unicode' object does not support item assignment
WARNING:Device:Failed to get current state!
WARNING:UtgGreedySearchPolicy:exception during sending events: 'NoneType' object has no attribute 'state_str'`

I use this command for testing:
droidbot -a /home/jyoti/VoiceNotify.apk -o /home/jyoti/droidbotres/ -is_emulator
My python version is 2.7.6.
and PATH variable contains path to android-platforms...

Please suggest how can I get rid of this error.

Thanks
