### ISSUE TITLE
Android-Trojan/SmsSend.247e9

### ISSUE THREAD

**Issue by bs111** [honeynet/droidbot#95]
很多引擎报告有木马， 大哥。

https://www.virustotal.com/gui/file-analysis/NTUyMDYwN2M4ZGY0MzU4NjFmMGUwZTg2MjRkMTVmNTk6MTU1NjE3OTc3OQ==/detection

**Comment by ylimit** [comment]
正常。因为代码用来测试的应用`droidbot/resources/DroidBoxTest.apk`本来就是一个恶意应用样本，会有很多恶意行为。
另外，该工具是面向各语言背景的开发者的，提issue时请尽量使用英文，谢谢。

**Comment by bs111** [comment]
Use other apks instead.
html files also have Trojan in it.
